micronaut:
  application:
    name: hello-world-java
# Uncomment to enable service discovery with Consul
#consul:
#    client:
#        registration:
#            enabled: true
#        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
