Micronaut for gRPC does not create client beans automatically for you. Instead, you must expose which client stubs your application needs using a `@Factory`.

You can dependency inject a `io.grpc.ManagedChannel` into the factory. Each injected `io.grpc.ManagedChannel` will automatically be shutdown when the application shuts down.

=== Configuring ManagedChannel Instances

The channel can be configured using properties defined under `grpc.client` by default.

For example, if you wish to disable secure communication:

[configuration]
----
grpc:
    client:
        plaintext: true
        max-retry-attempts: 10
----

Properties under `grpc.client` are global properties and are the defaults used unless named configuration exists under `grpc.channels.[NAME]`.

Any property of the `io.grpc.netty.NettyChannelBuilder` type can be configured.

You can also disable all gRPC client channel injection, or disable a specific named client:

[source,yaml]
----
grpc:
    client:
        enabled: false
----

[source,yaml]
----
grpc:
    client:
        greeter:
            enabled: false
----

When a client is disabled, optional or nullable `@GrpcChannel` injection points resolve to an empty value, while required injection points fail with a dependency injection error.

Alternatively if you prefer programmatic configuration you can write a `BeanCreatedEventListener` for example:

snippet::helloworld.ManagedChannelBuilderListener[tags="imports,clazz", source="main", title="Configuring the NettyChannelBuilder"]

[.lang-python]
--
NOTE: The Python listener customizes the `NettyChannelBuilder` of the `GrpcManagedChannelConfiguration` beans of the channels configured under `grpc.channels.[NAME]`: the self-referencing generic type `ManagedChannelBuilder<T extends ManagedChannelBuilder<T>>` cannot be used as the type argument of a `BeanCreatedEventListener` implemented in Python.
--

=== Auto Injected Types

By default, each channel will automatically be dependency injected with beans of the following types:

* `io.grpc.ClientInterceptor` - Any client interceptors declared as beans
* `io.grpc.NameResolver` - The configured name resolver

=== Creating Client Stub Beans

The value of the `@GrpcChannel` annotation can be used to specify the target server, the configuration for which can also be externalized:

snippet::helloworld.ExternalizedClients[tags="clazz", source="main"]

The above example requires that `my.server` and `my.port` are specified in `application.yml` (or via environment variables `MY_SERVER` and `MY_PORT`). You can also externalize this further into configuration and provide channel specific configuration.

For example given the following configuration:

[configuration]
----
grpc:
    channels:
        greeter:
            address: '${my.server}:${my.port}'
            plaintext: true
            max-retry-attempts: 10
----

You can then define the `@GrpcChannel` annotation as follows:

snippet::helloworld.NamedChannelClients[tags="clazz", source="main"]

The ID `greeter` is used to reference the configuration for `grpc.channels.greeter`.

Using service IDs in this way is the preferred way to set up gRPC clients, because it works nicely with Service Discovery (see the next section).

If you generate Reactor bindings with `reactive-grpc`, define the generated Reactor stub in the same kind of factory and inject the `ManagedChannel` with `@GrpcChannel`:

snippet::helloworld.ReactiveGreetingEndpointTest[tags="reactive-client", indent=0]

The resulting stub can then be injected into your application or tests and used directly with Reactor operators:

snippet::helloworld.ReactiveGreetingEndpointTest[tags="reactive-test"]
