Micronaut for gRPC does not create client beans automatically for you. Instead, you must expose which client stubs your application needs using a `@Factory`.

You can dependency inject a `io.grpc.ManagedChannel` into the factory. Each injected `io.grpc.ManagedChannel` will automatically be shutdown when the application shuts down.

=== Configuring ManagedChannel Instances

The channel can be configured using properties defined under `grpc.client` by default.

For example, if you wish to disable secure communication:

[source,yaml]
----
grpc:
    client:
        plaintext: true
        max-retry-attempts: 10
----

Properties under `grpc.client` are global properties and are the defaults used unless named configuration exists under `grpc.channels.[NAME]`.

Any property of the `io.grpc.netty.NettyChannelBuilder` type can be configured.

Alternatively if you prefer programmatic configuration you can write a `BeanCreationListener` for example:

.Configuring the NettyChannelBuilder
[source,java]
----
include::grpc-server-runtime/src/test/groovy/io/micronaut/grpc/ManagedChannelBuilderListener.java[]
----

=== Auto Injected Types

By default, each channel will automatically be dependency injected with beans of the following types:

* `io.grpc.ClientInterceptor` - Any client interceptors declared as beans
* `io.grpc.NameResolver` - The configured name resolver

=== Creating Client Stub Beans

The value of the `@GrpcChannel` annotation can be used to specify the target server, the configuration for which can also be externalized:

[source,java]
----
@Factory
class Clients {
    @Singleton
    GreeterGrpc.GreeterStub reactiveStub(
        @GrpcChannel("https://${my.server}:${my.port}")
        ManagedChannel channel) {
        return GreeterGrpc.newStub(
                channel
        );
    }
}
----

The above example requires that `my.server` and `my.port` are specified in `application.yml` (or via environment variables `MY_SERVER` and `MY_PORT`). You can also externalize this further into configuration and provide channel specific configuration.

For example given the following configuration:

[source,yaml]
----
grpc:
    channels:
        greeter:
            address: '${my.server}:${my.port}'
            plaintext: true
            max-retry-attempts: 10
----

You can then define the `@GrpcChannel` annotation as follows:

[source,java]
----
@Singleton
GreeterGrpc.GreeterStub reactiveStub(
    @GrpcChannel("greeter")
    ManagedChannel channel) {
    return GreeterGrpc.newStub(
            channel
    );
}
----

The ID `greeter` is used to reference the configuration for `grpc.channels.greeter`.

Using service IDs in this way is the preferred way to set up gRPC clients, because it works nicely with Service Discovery (see the next section).
