To get started you need first create a Micronaut project. The easiest way to do this is with the Micronaut Launch:

* Go to https://micronaut.io/launch/[Micronaut Launch]
* Select "gRPC Application" under "Application Type"
* Choose a Language / Build System etc.
* Click Generate

TIP: Replace `java` with `kotlin` or `groovy` to change language and the `build` flag with `maven` to use Maven instead.

Or alternatively you can create a project with `curl`:

[source,bash]
----
curl --location --request GET 'https://launch.micronaut.io/create/grpc/demo?lang=JAVA&build=GRADLE' --output demo.zip
unzip demo.zip -d demo
cd demo
----

To manually setup gRPC you can create an application:

[source,bash]
----
$ mn create-app helloworld
----

Then follow the below steps depending on the build system chosen.


=== Configuring Gradle

To configure Gradle, first apply the `com.google.protobuf` plugin:

[source,groovy]
----
plugins {
    ...
include::test-suite-java/build.gradle[tags=plugin]
}

----

Then configure the gRPC and protobuf plugins:

[source,groovy]
----
include::test-suite-java/build.gradle[tags=variables]

include::test-suite-java/build.gradle[tags=config]
----
NOTE: If you are using JDK9 or above, in order to avoid issues javax packages, provide the following compiler option to the grpc plugin to skip these stubs: `option '@generated=omit'` (added on link:https://github.com/grpc/grpc-java/releases/tag/v1.64.0[grpc-kava v1.64.0]) See discussion here: link:https://github.com/grpc/grpc-java/issues/9179[issue 9179]

[source,groovy]
----
    ...
    generateProtoTasks {
        all()*.plugins {
            grpc {
                option '@generated=omit'
            } }
    }
----

Use this configuration for Kotlin projects:

[source,groovy]
----
include::test-suite-kotlin/build.gradle[tags=variables]

dependencies {
...
include::test-suite-kotlin/build.gradle[tags=dependencies]
}

include::test-suite-kotlin/build.gradle[tags=config]

----

If you want to generate Reactor-based stubs with https://github.com/salesforce/reactive-grpc[reactive-grpc], add the generator plugin and stub dependency alongside the standard gRPC code generation:

[source,groovy]
----
include::test-suite-java/build.gradle[tags=reactive-variables]

dependencies {
...
include::test-suite-java/build.gradle[tags=reactive-dependencies]
}

sourceSets {
    main {
        java {
include::test-suite-java/build.gradle[tags=reactive-source-set]
        }
    }
}

protobuf {
...
include::test-suite-java/build.gradle[tags=reactive-plugin]
...
include::test-suite-java/build.gradle[tags=reactive-config]
}
----

Finally, add the following dependencies to your build:

For gRPC servers:

dependency:micronaut-grpc-server-runtime[groupId="io.micronaut.grpc"]

For gRPC clients:

dependency:micronaut-grpc-client-runtime[groupId="io.micronaut.grpc"]

NOTE: If you wish to use gRPC standalone without the Micronaut HTTP server you should comment out the `micronaut-http-server-netty` dependency.

You can then run:

[source,bash]
$ ./gradlew generateProto

To generate the Java sources from protobuf definitions in `src/main/proto`.

=== Configuring Maven

For Maven create a maven project first:

[source,bash]
----
$ mn create-app helloworld --build
----

Then configure the Protobuf plugin appropriately:

[source,xml]
----
include::test-suite-java/pom.xml[tags=plugin, indent=0]
----

You can then run:

[source,bash]
$ ./mvnw generate-sources

To generate the Java sources from protobuf definitions in `src/main/proto`.

=== Defining a Protobuf File

Once you have the build setup you can define a Protobuf file for your gRPC service. For example:

.src/main/proto/helloworld.proto
[source,protobuf]
----
include::test-suite-java/src/main/proto/helloworld.proto[]
----

TIP: With the Micronaut 1.1 or above CLI you can generate a service with `mn create-grpc-service helloworld` which will create the `proto` file and class that implements the stub.
