When using `@GrpcChannel` with a service ID without explicitly configuring the address of the service will trigger gRPC's `NameResolver` and attempt to do service discovery.

The default strategy for this is to use DNS based discovery. So for example you can do:

[source,java]
----
@GrpcChannel("dns://greeter")
----

Where DNS has been configured to know the address of the `greeter` service.

Alternatively, if you prefer to use a service discovery server then you can use integration with Micronaut service discovery.

=== Service Discovery with Consul

You can use Micronaut's built-in service discovery features with any supported server (Consul and Eureka currently).

The way in which this is done is the https://docs.micronaut.io/latest/guide/index.html#serviceDiscoveryConsul[same as a regular Micronaut service].

==== Registering a gRPC Service with Consul

To register a gRPC service with Consul first add the `micronaut-discovery-client` dependency:

dependency:micronaut-discovery-client[version="{version}", groupId="io.micronaut.discovery", scope="runtime"]

Then setup Consul correctly:

[source,yaml]
----
micronaut:
    application:
        name: greeter
consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
----

When using Service Discovery, Micronaut will register the service in Consul using the name defined in `micronaut.application.name`.
If the application also uses an HTTP Server (Netty, Tomcat,...), Micronaut will register the application with the same
name and a different port in Consul. In case you want to use a different name for the gRPC service in Consul:

[source,yaml]
----
micronaut:
    application:
        name: greeter # <1>
grpc:
    server:
        instance-id: 'hello-grpc' # <2>
----
<1> The HTTP port will be registered in Consul with the name `greeter`
<2> The gRPC port will be registered in Consul with the name `hello-grpc`


==== Discoverying Services via Consul

To discovery services via Consul and the Micronaut `DiscoveryClient` abstraction enable Consul and gRPC service discovery:

[source,yaml]
----
grpc:
    client:
        discovery:
            enabled: true
consul:
    client:
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
----

Then use the value `greeter` to discover the service when injecting the channel:

[source,java]
----
@Singleton
@Bean
GreeterGrpc.GreeterStub greeterStub(
    @GrpcChannel("greeter")
    ManagedChannel channel) {
    return GreeterGrpc.newStub(
            channel
    );
}
----