plugins {
    id "io.micronaut.build.internal.grpc-base"
    id 'org.graalvm.buildtools.native'
    id "io.micronaut.application"
}

dependencies {
    implementation platform(libs.boms.protobuf)
}

tasks.named("test") {
    useJUnitPlatform()
}

graalvmNative {
    toolchainDetection = false
    metadataRepository {
        enabled = true
    }
    binaries {
        all {
            resources.autodetect()
        }
    }
}
