pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    includeBuild "build-logic"
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.0-M12'
}

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

rootProject.name = 'grpc-parent'

include 'grpc-bom'
include 'grpc-annotation'
include 'grpc-client-runtime'
include 'grpc-server-runtime'
include 'grpc-runtime'
include 'protobuff-support'
include 'protobuff-json-support'

// documentation samples
include 'test-suite-java'
include 'test-suite-groovy'
include 'test-suite-kotlin'
include 'test-suite-protobuff-json-java'
include 'grpc-health'
include 'grpc-opentracing'

//experiemental feature so we're putting at the bottom
include 'protobuff-json-support'

micronautBuild {
    useStandardizedProjectNames = true
    importMicronautCatalog()
    importMicronautCatalog("micronaut-reactor")
    importMicronautCatalog("micronaut-tracing")
    importMicronautCatalog("micronaut-validation")
}
