plugins {
    id("groovy")
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.micronaut.application") version "4.4.4"
    id("io.micronaut.aot") version "4.4.4"
    id("com.google.protobuf") version "0.9.2"

}

version = "1.0.0-SNAPSHOT"
group = "com.example.services"

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    compileOnly("io.micronaut:micronaut-http-client")
    runtimeOnly("ch.qos.logback:logback-classic")
    testImplementation("io.micronaut:micronaut-http-client")
    implementation 'com.google.protobuf:protobuf-java-util'

    implementation("io.micronaut.grpc:micronaut-protobuff-json-support:4.9.0-SNAPSHOT")
    implementation("io.micronaut.grpc:micronaut-grpc-annotation:4.9.0-SNAPSHOT")
    runtimeOnly("io.micronaut.grpc:micronaut-grpc-server-runtime")
    testImplementation("io.micronaut.grpc:micronaut-grpc-server-runtime")
    implementation("javax.annotation:javax.annotation-api")
}


application {
    mainClass = "com.example.services.Application"
}
java {
    sourceCompatibility = JavaVersion.toVersion("21")
    targetCompatibility = JavaVersion.toVersion("21")
}


graalvmNative.toolchainDetection = false

micronaut {
    runtime("netty")
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("com.example.services.*", "io.micronaut.protobuf.json.*")

    }
    aot {
        // Please review carefully the optimizations enabled below
        // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
        replaceLogbackXml = true
    }
}


tasks.named("dockerfileNative") {
    jdkVersion = "21"
}

sourceSets {
    main {
        java {
            srcDirs("build/generated/source/proto/main/grpc")
            srcDirs("build/generated/source/proto/main/java")
        }
    }
}

protobuf {
    protoc { artifact = "com.google.protobuf:protoc:3.25.5" }
    plugins {
        grpc { artifact = "io.grpc:protoc-gen-grpc-java:1.68.1" }
    }
    generateProtoTasks {
        all()*.plugins { grpc {} }
    }
}


