plugins {
    id "io.micronaut.build.internal.grpc-base"
    id "io.micronaut.minimal.application"
}

tasks.named("test") {
    useJUnitPlatform()
}

//graalvmNative {
//    toolchainDetection = false
//    metadataRepository {
//        enabled = true
//    }
//    binaries {
//        all {
//            resources.autodetect()
//        }
//    }
//}
